### ISSUE TITLE
Question: why the need to specify arguments first?

### ISSUE THREAD

**Issue by jonaswindey** [ayatkevich/action-helper#1]
We defined the params on our action object:
`export const login = action('LOGIN', 'username', 'password');`
and supply params again when calling the object
`login({username: 'root', password: 'qwerty'})`

Wouldn't it be shorter to just call
`action('LOGIN')({username: 'root', password: 'qwerty'})` ?

**Comment by ayatkevich** [comment]
@jonaswindey thanks for asking. It would definitely shorter to just pass any data right to the action.

However, I've designed this particular helper to work with specified types. So I could implement my reducers to just merge the data from the action into the state. Therefore, I need to be sure that action holds the data that I want to.

Moreover, that's not a bad idea. And I'm going to update the helper so it could work also that way!

Thanks @jonaswindey

**Comment by ayatkevich** [comment]
@jonaswindey thank you for the contribution!
